export const ALL_MUSIC_PAGE = 'ALL_MUSIC_PAGE'
export const ALL_MUSIC_PAGE_SUCCESS = 'ALL_MUSIC_PAGE_SUCCESS'
export const ALL_MUSIC_PAGE_FAILURE = 'ALL_MUSIC_PAGE_FAILURE'
export const ALL_MUSIC_PAGE_RESET = 'ALL_MUSIC_PAGE_RESET'
