export const UPLOADED_PICTURES = 'UPLOADED_PICTURES'
export const UPLOADED_PICTURES_SUCCESS = 'UPLOADED_PICTURES_SUCCESS'
export const UPLOADED_PICTURES_FAILURE = 'UPLOADED_PICTURES_FAILURE'
export const UPLOADED_PICTURES_RESET = 'UPLOADED_PICTURES_RESET'
