export const PICTURE_RECOMMENDED = 'PICTURE_RECOMMENDED'
export const PICTURE_RECOMMENDED_SUCCESS = 'PICTURE_RECOMMENDED_SUCCESS'
export const PICTURE_RECOMMENDED_FAILURE = 'PICTURE_RECOMMENDED_FAILURE'
export const PICTURE_RECOMMENDED_RESET = 'PICTURE_RECOMMENDED_RESET'
