export const GET_ALL_FEEDS = 'GET_ALL_FEEDS'
export const GET_ALL_FEEDS_SUCCESS = 'GET_ALL_FEEDS_SUCCESS'
export const GET_ALL_FEEDS_FAILURE = 'GET_ALL_FEEDS_FAILURE'
export const GET_ALL_FEEDS_RESET = 'GET_ALL_FEEDS_RESET'