export const TRENDING_VIDEOS = 'TRENDING_VIDEOS'
export const TRENDING_VIDEOS_SUCCESS = 'TRENDING_VIDEOS_SUCCESS'
export const TRENDING_VIDEOS_FAILURE = 'TRENDING_VIDEOS_FAILURE'
export const TRENDING_VIDEOS_RESET = 'TRENDING_VIDEOS_RESET'
