export const GET_ALL_PICTUREVIEW = 'GET_ALL_PICTUREVIEW'
export const GET_ALL_PICTUREVIEW_SUCCESS = 'GET_ALL_PICTUREVIEW_SUCCESS'
export const GET_ALL_PICTUREVIEW_FAILURE = 'GET_ALL_PICTUREVIEW_FAILURE'