export const GET_CUSTOMIZED_FEEDS = 'GET_CUSTOMIZED_FEEDS'
export const GET_CUSTOMIZED_FEEDS_SUCCESS = 'GET_CUSTOMIZED_FEEDS_SUCCESS'
export const GET_CUSTOMIZED_FEEDS_FAILURE = 'GET_CUSTOMIZED_FEEDS_FAILURE'