export const TRENDING_AUDIOS = 'TRENDING_AUDIOS'
export const TRENDING_AUDIOS_SUCCESS = 'TRENDING_AUDIOS_SUCCESS'
export const TRENDING_AUDIOS_FAILURE = 'TRENDING_AUDIOS_FAILURE'
export const TRENDING_AUDIOS_RESET = 'TRENDING_AUDIOS_RESET'
