export const GET_ORDER_DETAIL = 'GET_ORDER_DETAIL'
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS'
export const GET_ORDER_DETAIL_FAILURE = 'GET_ORDER_DETAIL_FAILURE'
export const GET_ORDER_DETAIL_RESET = 'GET_ORDER_DETAIL_RESET'