export const BENEFICIARY_LIST = 'BENEFICIARY_LIST'
export const BENEFICIARY_LIST_SUCCESS = 'BENEFICIARY_LIST_SUCCESS'
export const BENEFICIARY_LIST_FAILURE = 'BENEFICIARY_LIST_FAILURE'
export const BENEFICIARY_LIST_RESET = 'BENEFICIARY_LIST_RESET'