export const ALL_VIDEO_PAGE = 'ALL_VIDEO_PAGE'
export const ALL_VIDEO_PAGE_SUCCESS = 'ALL_VIDEO_PAGE_SUCCESS'
export const ALL_VIDEO_PAGE_FAILURE = 'ALL_VIDEO_PAGE_FAILURE'
export const ALL_VIDEO_PAGE_RESET = 'ALL_VIDEO_PAGE_RESET'
