export const GET_TRENDING_BLOGS_COMMENT = 'GET_TRENDING_BLOGS_COMMENT'
export const GET_TRENDING_BLOGS_COMMENT_SUCCESS = 'GET_TRENDING_BLOGS_COMMENT_SUCCESS'
export const GET_TRENDING_BLOGS_COMMENT_FAILURE = 'GET_TRENDING_BLOGS_COMMENT_FAILURE'

