export const GET_ALL_BLOGCAT_LIST = 'GET_ALL_BLOGCAT_LIST'
export const GET_ALL_BLOGCAT_LIST_SUCCESS = 'GET_ALL_BLOGCAT_LIST_SUCCESS'
export const GET_ALL_BLOGCAT_LIST_FAILURE = 'GET_ALL_BLOGCAT_LIST_FAILURE'
