export const TRENDING_PICTURES = 'TRENDING_PICTURES'
export const TRENDING_PICTURES_SUCCESS = 'TRENDING_PICTURES_SUCCESS'
export const TRENDING_PICTURES_FAILURE = 'TRENDING_PICTURES_FAILURE'
export const TRENDING_PICTURES_RESET = 'TRENDING_PICTURES_RESET'
