export const GET_BLOGS_COMMENT_REPLY = 'GET_BLOGS_COMMENT_REPLY'
export const GET_BLOGS_COMMENT_REPLY_SUCCESS = 'GET_BLOGS_COMMENT_REPLYSUCCESS'
export const GET_BLOGS_COMMENT_REPLY_FAILURE = 'GET_BLOGS_COMMENT_REPLYFAILURE'
export const GET_BLOGS_COMMENT_REPLY_RESET = 'GET_BLOGS_COMMENT_REPLYRESET'

