export const GET_TRENDING_VIDEOS = 'GET_TRENDING_VIDEOS'
export const GET_TRENDING_VIDEOS_SUCCESS = 'GET_TRENDING_VIDEOS_SUCCESS'
export const GET_TRENDING_VIDEOS_FAILURE = 'GET_TRENDING_VIDEOS_FAILURE'