export const UPLOADED_AUDIO = 'UPLOADED_AUDIO'
export const UPLOADED_AUDIO_SUCCESS = 'UPLOADED_AUDIO_SUCCESS'
export const UPLOADED_AUDIO_FAILURE = 'UPLOADED_AUDIO_FAILURE'
export const UPLOADED_AUDIO_RESET = 'UPLOADED_AUDIO_RESET'
