export const MY_USER_PROFILE = 'MY_USER_PROFILE'
export const MY_USER_PROFILE_SUCCESS = 'MY_USER_PROFILE_SUCCESS'
export const MY_USER_PROFILE_FAILURE = 'MY_USER_PROFILE_FAILURE'
export const MY_USER_PROFILE_RESET = 'MY_USER_PROFILE_RESET'