export const DELETE_DATA= 'DELETE_DATA'
export const DELETE_DATA_SUCCESS= 'DELETE_DATA_SUCCESS'
export const DELETE_DATA_FAILURE= 'DELETE_DATA_FAILURE'
export const DELETE_DATA_RESET= 'DELETE_DATA_RESET'