export const EMI_DETAILS = 'EMI_DETAILS'
export const EMI_DETAILS_SUCCESS = 'EMI_DETAILS_SUCCESS'
export const EMI_DETAILS_FAILURE = 'EMI_DETAILS_FAILURE'
export const EMI_DETAILS_RESET = 'EMI_DETAILS_RESET'