export const GET_ALL_VIDEOCATLIST = 'GET_ALL_VIDEOCATLIST'
export const GET_ALL_VIDEOCATLIST_SUCCESS = 'GET_ALL_VIDEOCATLIST_SUCCESS'
export const GET_ALL_VIDEOCATLIST_FAILURE = 'GET_ALL_VIDEOVIEW_FAILURE'