export const TRENDING_BLOGS = 'TRENDING_BLOGS'
export const TRENDING_BLOGS_SUCCESS = 'TRENDING_BLOGS_SUCCESS'
export const TRENDING_BLOGS_FAILURE = 'TRENDING_BLOGS_FAILURE'
export const TRENDING_BLOGS_RESET = 'TRENDING_BLOGS_RESET'
