export const GET_ALL_VIDEOLIST = 'GET_ALL_VIDEOLIST'
export const GET_ALL_VIDEOLIST_SUCCESS = 'GET_ALL_VIDEOLIST_SUCCESS'
export const GET_ALL_VIDEOLIST_FAILURE = 'GET_ALL_VIDEOLIST_FAILURE'
export const GET_ALL_VIDEOLIST_RESET = 'GET_ALL_VIDEOLIST_RESET'