export const NOTIFICATION = 'NOTIFICATION'
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS'
export const NOTIFICATION_FAILURE = 'NOTIFICATION_FAILURE'
export const NOTIFICATION_RESET = 'NOTIFICATION_RESET'
