export const SUBSCRIBE = 'SUBSCRIBE'
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS'
export const SUBSCRIBE_FAILURE = 'SUBSCRIBE_FAILURE'
export const SUBSCRIBE_RESET = 'SUBSCRIBE_RESET'


export const UNSUBSCRIBE = 'UNSUBSCRIBE'
export const UNSUBSCRIBE_SUCCESS = 'UNSUBSCRIBE_SUCCESS'
export const UNSUBSCRIBE_FAILURE = 'UNSUBSCRIBE_FAILURE'
export const UNSUBSCRIBE_RESET = 'UNSUBSCRIBE_RESET'