export const INTERNSHIP_REGISTER_MAP = 'INTERNSHIP_REGISTER_MAP'
export const INTERNSHIP_REGISTER_MAP_SUCCESS = 'INTERNSHIP_REGISTER_MAP_SUCCESS'
export const INTERNSHIP_REGISTER_MAP_FAILURE = 'INTERNSHIP_REGISTER_MAP_FAILURE'
export const INTERNSHIP_REGISTER_MAP_RESET = 'INTERNSHIP_REGISTER_MAP_RESET'