export const UPLOADED_BLOG = 'UPLOADED_BLOG'
export const UPLOADED_BLOG_SUCCESS = 'UPLOADED_BLOG_SUCCESS'
export const UPLOADED_BLOG_FAILURE = 'UPLOADED_BLOG_FAILURE'
export const UPLOADED_BLOG_RESET = 'UPLOADED_BLOG_RESET'
