export const CONNECT = 'CONNECT'
export const CONNECT_SUCCESS = 'CONNECT_SUCCESS'
export const CONNECT_FAILURE = 'CONNECT_FAILURE'
export const CONNECT_RESET = 'CONNECT_RESET'

export const CONNECT_CONFIRM = 'CONNECT_CONFIRM'
export const CONNECT_CONFIRM_SUCCESS = 'CONNECT_CONFIRM_SUCCESS'
export const CONNECT_CONFIRM_FAILURE = 'CONNECT_CONFIRM_FAILURE'
export const CONNECT_CONFIRM_RESET = 'CONNECT_CONFIRM_RESET'

export const CONNECT_REJECT = 'CONNECT_REJECT'
export const CONNECT_REJECT_SUCCESS = 'CONNECT_REJECT_SUCCESS'
export const CONNECT_REJECT_FAILURE = 'CONNECT_REJECT_FAILURE'
export const CONNECT_REJECT_RESET = 'CONNECT_REJECT_RESET'