export const TOKEN_GENERATION = 'TOKEN_GENERATION'
export const TOKEN_GENERATION_SUCCESS = 'TOKEN_GENERATION_SUCCESS'
export const TOKEN_GENERATION_FAILURE = 'TOKEN_GENERATION_FAILURE'
export const TOKEN_GENERATION_RESET = 'TOKEN_GENERATION_RESET'
