export const VERIFY_UPDATED_DATA = 'VERIFY_UPDATED_DATA'
export const VERIFY_UPDATED_DATA_SUCCESS = 'VERIFY_UPDATED_DATA_SUCCESS'
export const VERIFY_UPDATED_DATA_FAILURE = 'VERIFY_UPDATED_DATA_FAILURE'