export const SUBSCRIPTION_LIST = 'SUBSCRIPTION_LIST'
export const SUBSCRIPTION_LIST_SUCCESS = 'SUBSCRIPTION_LIST_SUCCESS'
export const SUBSCRIPTION_LIST_FAILURE = 'SUBSCRIPTION_LIST_FAILURE'
export const SUBSCRIPTION_LIST_RESET = 'SUBSCRIPTION_LIST_RESET'
