export const VERIFY_REFERRAL = 'VERIFY_REFERRAL'
export const VERIFY_REFERRAL_SUCCESS = 'VERIFY_REFERRAL_SUCCESS'
export const VERIFY_REFERRAL_FAILURE = 'VERIFY_REFERRAL_FAILURE'
export const VERIFY_REFERRAL_RESET = 'VERIFY_REFERRAL_RESET'
