export const NEW_USER_LOGIN = 'NEW_USER_LOGIN'
export const NEW_USER_LOGIN_SUCCESS = 'NEW_USER_LOGIN_SUCCESS'
export const NEW_USER_LOGIN_FAILURE = 'NEW_USER_LOGIN_FAILURE'
export const NEW_USER_LOGIN_RESET = 'NEW_USER_LOGIN_RESET'