export const UPLOADED_VIDEOS = 'UPLOADED_VIDEOS'
export const UPLOADED_VIDEOS_SUCCESS = 'UPLOADED_VIDEOS_SUCCESS'
export const UPLOADED_VIDEOS_FAILURE = 'UPLOADED_VIDEOS_FAILURE'
export const UPLOADED_VIDEOS_RESET = 'UPLOADED_VIDEOS_RESET'
