export const GET_REPORT_CATEGORIES = 'GET_REPORT_CATEGORIES'
export const GET_REPORT_CATEGORIES_SUCCESS = 'GET_REPORT_CATEGORIES_SUCCESS'
export const GET_REPORT_CATEGORIES_FAILURE = 'GET_REPORT_CATEGORIES_FAILURE'


export const POST_REPORT = 'POST_REPORT'
export const POST_REPORT_SUCCESS = 'POST_REPORT_SUCCESS'
export const POST_REPORT_FAILURE = 'POST_REPORT_FAILURE'