export const GET_TOP_CATEGORY_VIDEOS = 'GET_TOP_CATEGORY_VIDEOS'
export const GET_TOP_CATEGORY_VIDEOS_SUCCESS = 'GET_TOP_CATEGORY_VIDEOS_SUCCESS'
export const GET_TOP_CATEGORY_VIDEOS_FAILURE = 'GET_TOP_CATEGORY_VIDEOS_FAILURE'