export const GET_MUSIC_COMMENT_LIST = 'GET_MUSIC_COMMENT_LIST'
export const GET_MUSIC_COMMENT_LIST_SUCCESS = 'GET_MUSIC_COMMENT_LIST_SUCCESS'
export const GET_MUSIC_COMMENT_LIST_FAILURE = 'GET_MUSIC_COMMENT_LIST_FAILURE'