export const VIDEO_RECOMMENDED = 'VIDEO_RECOMMENDED'
export const VIDEO_RECOMMENDED_SUCCESS = 'VIDEO_RECOMMENDED_SUCCESS'
export const VIDEO_RECOMMENDED_FAILURE = 'VIDEO_RECOMMENDED_FAILURE'
export const VIDEO_RECOMMENDED_RESET = 'VIDEO_RECOMMENDED_RESET'
