export const GET_ALL_AUDIOCATLIST = 'GET_ALL_AUDIOCATLIST'
export const GET_ALL_AUDIOCATLIST_SUCCESS = 'GET_ALL_AUDIOCATLIST_SUCCESS'
export const GET_ALL_AUDIOCATLIST_FAILURE = 'GET_ALL_AUDIOVIEW_FAILURE'