export const INTERNSHIP_SUBJECTS = 'INTERNSHIP_SUBJECTS'
export const INTERNSHIP_SUBJECTS_SUCCESS = 'INTERNSHIP_SUBJECTS_SUCCESS'
export const INTERNSHIP_SUBJECTS_FAILURE = 'INTERNSHIP_SUBJECTS_FAILURE'
export const INTERNSHIP_SUBJECTS_RESET = 'INTERNSHIP_SUBJECTS_RESET'