export const GET_ALL_PICTURES = 'GET_ALL_PICTURES'
export const GET_ALL_PICTURES_SUCCESS = 'GET_ALL_PICTURES_SUCCESS'
export const GET_ALL_PICTURES_FAILURE = 'GET_ALL_PICTURES_FAILURE'
export const GET_ALL_PICTURES_LIST_BY_CATEGORY = 'GET_ALL_PICTURES_LIST_BY_CATEGORY'
export const GET_PICTURES_BY_CATEGORIES="GET_PICTURES_BY_CATEGORIES"