export const GET_ALL_BLOG_CATEGORIES = 'GET_ALL_BLOG_CATEGORIES'
export const GET_ALL_BLOG_CATEGORIES_SUCCESS = 'GET_ALL_BLOG_CATEGORIES_SUCCESS'
export const GET_ALL_BLOG_CATEGORIES_FAILURE = 'GET_ALL_BLOG_CATEGORIES_FAILURE'


