export const ALL_BLOG_PAGE = 'ALL_BLOG_PAGE'
export const ALL_BLOG_PAGE_SUCCESS = 'ALL_BLOG_PAGE_SUCCESS'
export const ALL_BLOG_PAGE_FAILURE = 'ALL_BLOG_PAGE_FAILURE'
export const ALL_BLOG_PAGE_RESET = 'ALL_BLOG_PAGE_RESET'
