export const MAKE_CUSTOMIZE = 'MAKE_CUSTOMIZE'
export const MAKE_CUSTOMIZE_SUCCESS = 'MAKE_CUSTOMIZE_SUCCESS'
export const MAKE_CUSTOMIZE_FAILURE = 'MAKE_CUSTOMIZE_FAILURE'
export const MAKE_CUSTOMIZE_RESET = 'MAKE_CUSTOMIZE_RESET'