export const UPLOAD_COVER_PIC = 'UPLOAD_COVER_PIC'
export const UPLOAD_COVER_PIC_SUCCESS = 'UPLOAD_COVER_PIC_SUCCESS'
export const UPLOAD_COVER_PIC_FAILURE = 'UPLOAD_COVER_PIC_FAILURE'
export const UPLOAD_COVER_PIC_RESET = 'UPLOAD_COVER_PIC_RESET'