export const BLOG_RECOMMENDED = 'BLOG_RECOMMENDED'
export const BLOG_RECOMMENDED_SUCCESS = 'BLOG_RECOMMENDED_SUCCESS'
export const BLOG_RECOMMENDED_FAILURE = 'BLOG_RECOMMENDED_FAILURE'
export const BLOG_RECOMMENDED_RESET = 'BLOG_RECOMMENDED_RESET'
