export const GET_ALL_AUDIOS_ITEMS = 'GET_ALL_AUDIOS_ITEMS'
export const GET_ALL_AUDIOS_ITEMS_SUCCESS = 'GET_ALL_AUDIOS_ITEMS_SUCCESS'
export const GET_ALL_AUDIOS_ITEMS_FAILURE = 'GET_ALL_AUDIOS_ITEMS_FAILURE'
export const GET_MUSIC_ITEMS_FROM_ALL_COMPONENTS = 'GET_PARTICULAR_MUSIC_ITEM'