export const GET_ALL_CHANGEPASSWORD = 'GET_ALL_CHANGEPASSWORD'
export const GET_ALL_CHANGEPASSWORD_SUCCESS = 'GET_ALL_CHANGEPASSWORD_SUCCESS'
export const GET_ALL_CHANGEPASSWORD_FAILURE = 'GET_ALL_CHANGEPASSWORD_FAILURE'