export const ADD_BENEFICIARY = 'ADD_BENEFICIARY'
export const ADD_BENEFICIARY_SUCCESS = 'ADD_BENEFICIARY_SUCCESS'
export const ADD_BENEFICIARY_FAILURE = 'ADD_BENEFICIARY_FAILURE'
export const ADD_BENEFICIARY_RESET = 'ADD_BENEFICIARY_RESET'
