export const GET_CONNECTION_LIST = 'GET_CONNECTION_LIST'
export const GET_CONNECTION_LIST_SUCCESS = 'GET_CONNECTION_LIST_SUCCESS'
export const GET_CONNECTION_LIST_FAILURE = 'GET_CONNECTION_LIST_FAILURE'
export const GET_CONNECTION_LIST_RESET = 'GET_CONNECTION_LIST_RESET'