export const EDIT_PICTURE = 'EDIT_PICTURE'
export const EDIT_PICTURE_SUCCESS = 'EDIT_PICTURE_SUCCESS'
export const EDIT_PICTURE_FAILURE = 'EDIT_PICTURE_FAILURE'
export const EDIT_PICTURE_RESET = 'EDIT_PICTURE_RESET'